name: Go

on: [push, pull_request]

jobs:

  build:
    name: Build
    runs-on: windows-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      
    - name: Get goversioninfo
      run: go get github.com/josephspurrier/goversioninfo/cmd/goversioninfo

    - name: Install goversioninfo
      run: go install github.com/josephspurrier/goversioninfo/cmd/goversioninfo

    - name: Build
      shell: cmd
      run: build.bat
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      if: runner.os == 'Windows'
      with:
        # Artifact name
        name: ${{ runner.os }} # optional, default is artifact
        # A file, directory or wildcard pattern that describes what to upload
        path: WinCryptSSHAgent*.exe
